version: '3'

services:
  db:
    image: mysql
    env_file:
      - variables.env

  web:
    depends_on:
      - db
    build: web
    env_file:
      - variables.env
    ports:
      - 8000:80

  app:
    depends_on:
      - db
    build: backend
    env_file:
      - variables.env
