---
# tasks file for database

- name: run the equivalent of apt-get update before the operation
  become: true
  apt:
    update_cache: yes

- name: installing softwares for database
  become: true
  apt:
    name:
      - mysql-server
      - mysql-client
      - python3-pip
      - libmysqlclient-dev

- name: start mysql service
  become: true
  service: 
    name: mysql
    state: started

- name: Install mysqlclient
  pip:
    name: mysqlclient
  become: true

- name: copy mysqld.cnf to instance
  become: true
  copy:
    src: mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  register: mysql_setup

- name: restart mysql
  become: true
  systemd:
    name: mysql
    state: restarted
  when: mysql_setup.changed

- name: create backend database on localhost
  mysql_db:
    login_host: "{{ db_host }}"
    name: "{{ db_name }}"
  become: true
  when: db_host == "localhost"

- name: create backend database when not on localhost
  mysql_db:
    name: "{{ db_name }}"
  become: true
  when: db_host != "localhost"

- name: create mysql user on localhost
  mysql_user:
    host: "%"
    login_host: "{{ db_host }}"
    name: "{{ db_username }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
  become: true
  when: db_host == "localhost"

- name: create mysql user when not on localhost
  mysql_user:
    host: "%"
    name: "{{ db_username }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
  become: true
  when: db_host != "localhost"
